name: dbt_portfolio
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"


models:
  dbt_portfolio:

    p1_jaffle_shop:
  
      +schema: jaffle_shop
  
      1_staging:
        +materialized: view

      2_intermediate:
        +materialized: view
  
      3_marts:
        +materialized: table